### ISSUE TITLE
The client side code is simple yet efficient, but it could still be improved

### ISSUE THREAD

**Issue by Razpudding** [TimoVerkroost/minor-real-time-web-api#6]
It's a little bit dirty to write and manipulate html and css straight from js though. It would already be a lot nicer if you had a function that generated a html node for each country. That would make it more readable and it would also clearly show where the information comes from.

You could have one function that generates the nodes, and one function that updates its properties. Then you would also have the added benefit that you don't have to repeat any of the code like

```document.getElementById(listCount[i].code).style.order = '-' + listCount[i].count;```

**Comment by TimoVerkroost** [comment]
I tried it the JS way but this was faster and I wanted to know if I can combine JS and CSS to order elements. For know I think this is the best solution.
